# Generated by Django 4.2.5 on 2023-09-06 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_roundcurrentvalues_remove_values_round_delete_round_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
